# Generated by Django 3.1.2 on 2020-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ignored', 'Ignored'), ('replied', 'Replied')], default='pending', max_length=15, verbose_name='Status'),
        ),
    ]
