# Generated by Django 3.1.2 on 2020-11-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_request_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='recipients',
        ),
        migrations.AddField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='feedback.user', verbose_name='Requested from'),
            preserve_default=False,
        ),
    ]
