# Generated by Django 3.1.2 on 2020-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('bot_token', models.CharField(max_length=64, verbose_name='Bot Token')),
            ],
            options={
                'verbose_name': 'Slack Team',
                'verbose_name_plural': 'Slack Teams',
            },
        ),
    ]
